rapidsai/ucx-split-feedstock

- .ci_support/linux_cuda_compiler_version10.0.yaml
- .ci_support/linux_cuda_compiler_version10.1.yaml
- .ci_support/linux_cuda_compiler_version9.2.yaml
- .ci_support/linux_cuda_compiler_versionNone.yaml
- README.md
- recipe/install_ucx-py.sh
- recipe/install_ucx.sh
- recipe/meta.yaml
Ports PR ( https://github.com/conda-forge/ucx-split-feedstock/pull/4 ) to the rapidsai feedstock. Like PR ( https://github.com/rapidsai/ucx-split-feedstock/pull/2 ) this adds the Python bits for gpuCI work on this feedstock.
cc @mike-wendt
> Add ucx-py

- recipe/meta.yaml
This PR bumps ucx to latest in branch 1.7.X and latest in ucx-py branch 0.10.  I don't think the ucx-py bump is necessary but thought it would be nicer if it doesn't fall too far out of date.
> bump ucx and ucxpy

- .gitattributes
- .scripts/build_steps.sh
- README.md
- recipe/meta.yaml
- recipe/yum_requirements.txt
Request from @jakirkham and @quasiben and following https://github.com/jakirkham-feedstocks/ucx-split-feedstock/commit/e4a1bd1a7bedeccb77bd0e0057ea063339bdb6bb
> ENH Add CDT for `libibcm-devel`

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_cuda_compiler_version10.2.yaml
- .gitattributes
- .scripts/build_steps.sh
- README.md
- recipe/install_ucx.sh
- recipe/ipc-cache-threshold.patch
- recipe/meta.yaml
- recipe/yum_requirements.txt
* Update to OpenUCX version 1.7.0
* Include IPC Cache Threshold patch ( https://github.com/rapidsai/ucx-split-feedstock/pull/7#issuecomment-575843842 ) ( https://github.com/rapidsai/ucx-split-feedstock/pull/7#issuecomment-576357640 )
* Enable IB Connection Manager support (with required CDTs/system packages)
* Enable Cross Memory Attach (fixes have been applied upstream)
* Add other (already enabled) flags to be explicit
* Switch to using sysroot build for better compatibility with Anaconda compilers and CDTs
* Add CUDA 10.2
* Require Cython 0.29.14+
* Re-renders the feedstock to update the build scripts accordingly
> Release 1.7.0 and miscellaneous improvements

- ci/axis/nightly.yml
After the 0.12 release we no longer need to build nightlies, also CUDA 9.2 is no longer supported in 0.13
> Remove branch-0.12 from nightly and CUDA 9.2

- recipe/meta.yaml
This should pick up the correct CUDA based on the specified cudatoolkit
> FIX Pin ucx-py to ucx version not build string

- recipe/meta.yaml
- recipe/stream_refcount_v1.7.0.patch
Adds a patch based on PR ( https://github.com/openucx/ucx/pull/4646 ) backported for 1.7.0.
cc @mike-wendt @quasiben @pentschev
> Add stream refcount patch

- .github/CODEOWNERS
- .github/workflows/main.yml
- .github/workflows/webservices.yml
- README.md
- recipe/meta.yaml
Include people more actively involved in the recipe at present to ensure the right people are requested for reviews and we are not generating noise for others.
> Update the recipe's maintainer list

- recipe/ib_registration_cache.patch
As it appears there are issues loading `libucm_cuda`, which also links to `libcuda`, make sure the we link to `libcuda` last. This way if `libucm_cuda` loads `libcuda`, we don't clash with it.
xref: https://github.com/rapidsai/ucx-py/issues/435#issuecomment-596012583
cc @quasiben @pentschev
> Link `libcuda` last

- recipe/meta.yaml
ucx should be built/uploaded under all CUDA versions
ucx-py should only be built/uploaded under a single (10.2) CUDA version
I think this changes enforces that.
> Fix ucx-py uploads

- recipe/meta.yaml
As `ucx-py` is agnostic to CPU/GPU builds, there is no need to have this constraint to determine whether a CPU or GPU build of `ucx-py` is installed (such a thing doesn't exist). So drop this constraint so it can be used easily in both cases.
> Drop `run_constrained` from `ucx-py`

- recipe/install_ucx-py.sh
While [conda-build does configure pip to not install dependencies amongst other things]( https://github.com/conda/conda-build/blob/ba6cf7ab75de9f7961e1ce85c090baf52ce46cbc/conda_build/build.py#L2426-L2440 ), that does not appear to be respected here. So add in our own pip flags to ensure that dependencies are not getting installed and included in the package.
cc @quasiben (this should fix the issue we saw earlier)
> Ensure dependencies are not installed

- recipe/meta.yaml
For RC versions UCX sometimes includes a `-`. Unfortunately this is not something Conda likes. So just drop the `-`. There don't appear to be other `-`s in the version. So this should only affect these RC cases.
> Drop `-` in UCX version

- .ci_support/migrations/python38.yaml
This ensure that when using `conda smithy` to re-render the feedstock, Python 3.8 is kept. This file is taken from conda-forge were it is used for the Python 3.8 migration there.
> Add Python 3.8 migration for ucx-py

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_cuda_compiler_version10.0.yaml
- .ci_support/linux_cuda_compiler_version10.1.yaml
- .ci_support/linux_cuda_compiler_version10.2.yaml
- .ci_support/linux_cuda_compiler_versionNone.yaml
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- README.md
- recipe/conda_build_config.yaml
Fixes https://github.com/rapidsai/ucx-split-feedstock/issues/33
Reverts the compiler pinning in commit ( https://github.com/rapidsai/ucx-split-feedstock/commit/855b11345377ebf3ed786dd8dd1aade41d970ae9 ) and re-renders, which realigns this feedstock with conda-forge (on GCC 7.5).
cc @mike-wendt
> Relax compiler pinning

- .ci_support/migrations/python38.yaml
- recipe/meta.yaml
Closes https://github.com/rapidsai/ops/issues/1019
Drops Python 3.6 builds of `ucx-py`. CUDA 10.0 was dropped in PR ( https://github.com/rapidsai/ucx-split-feedstock/pull/34 ).
Note that migration files and variant files still show Python 3.6. However these are not actually built (as I verified locally).
cc @mike-wendt
> Drop Python 3.6

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_cuda_compiler_version10.1.yaml
- .ci_support/linux_64_cuda_compiler_version10.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .scripts/build_steps.sh
- LICENSE.txt
- README.md
- ci/cpu/build.sh
- recipe/install_ucx.sh
- recipe/meta.yaml
- recipe/yum_requirements.txt
This drops `ibverbs` from the `ucx` package. We are doing this as using the `ibverbs` package from CentOS 6 does not appear to be sufficient when reusing `ucx` packages built against it with OFED.
> Drop ibverbs

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_cuda_compiler_version10.1.yaml
- .ci_support/linux_64_cuda_compiler_version10.2.yaml
- .ci_support/linux_64_cuda_compiler_version11.0.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- README.md
- ci/axis/nightly.yml
- ci/axis/release.yml
- ci/cpu/build.sh
- recipe/conda_build_config.yaml
- recipe/meta.yaml
Follows #40 and adds CUDA 11 support based on initial work in #37 
Uses custom CUDA 11 anvil until a conda-forge one is available. Re-rendered but there is an issue with the CUDA 11 template. I've had to add a custom patch to it [here](https://github.com/rapidsai/ucx-split-feedstock/pull/41/commits/c7a397733f1ee750df49418a99dc3be446fd8ce6), as these [lines](https://github.com/rapidsai/ucx-split-feedstock/blob/enh-cuda11-noib/recipe/conda_build_config.yaml#L7-L8) in the `conda_build_config.yaml` do not work.
> ENH CUDA 11 support without IB

- ci/axis/nightly.yml
- ci/axis/release.yml
With the default branch changes we need to build from `main` instead to get the correct git tags for release builds.
> FIX Build ucx-py from main branch for release

- ci/axis/nightly.yml
For integration pkgs, `cugraph`, `cuxfilter`, and `cuml` all need `ucx-py` 0.17
> ENH Enable branch-0.17 builds

- ci/axis/nightly.yml
Unblocks conda builds for v0.18 that are failing and thereby unblocks the following:
- rapidsai/integration#180
- rapidsai/gpuci-build-environment#149
- rapidsai/docker#222
> ENH Enable branch-0.18 builds

- recipe/meta.yaml
`libhwloc` 2.4.0 requires `libgcc-ng>=9.3.0` but we're still on 7.5, so restrict libhwloc to a compatible version
> Update libhwloc version

- ci/axis/nightly.yml
Just enable builds for `branch-0.20`.
> Add v0.20 to nightly builds

- ci/axis/nightly-arm64.yml
- ci/axis/nightly.yml
- ci/axis/release-arm64.yml
- ci/axis/release.yml
- recipe/meta.yaml
We've been testing 1.11.2 nightly for about a month now and do not know of any issues with that upgrade, plus it fixes a few error handling issues from UCX 1.11.1.
> Update to UCX 1.11.2

- ci/cpu/build.sh
This PR ensures that at least version `3.21.6` of `conda-build` is installed since previous versions seem to be having issues.
> Ensure working `conda-build` version is used

- ci/axis/nightly.yml
- ci/axis/release.yml
The `gpuci` image entries here are leftover from before CUDA Enhanced Compatibility builds were a thing. They are no longer used and can therefore be removed.
> Remove extraneous `gpuci` images

- recipe/meta.yaml
Reverts rapidsai/ucx-split-feedstock#63
Can't use `cuda_major` due to needing both a CUDA 11.0 and 11.2+ build.
> Revert "Update `conda` recipes for Enhanced Compatibility effort"

- ci/axis/nightly-arm64.yml
- ci/axis/nightly.yml
- ci/axis/release-arm64.yml
- ci/axis/release.yml
- recipe/meta.yaml
Latest UCX 1.12.0 nightly tests have been successful, so we should be good moving to this release from last week.
> Update to UCX 1.12.0

- ci/axis/nightly-arm64.yml
- ci/axis/nightly.yml
This PR adds `branch-0.25` to our axis files that are used for CI builds. This will ensure that `0.25` packages get published for `ucx-py`.
> Add `branch-0.25` to CI builds
